import bcrypt from 'bcryptjs';

export const data = {
    users: [
        {
            name: 'Ronak',
            email: 'admin@fhub.com',
            password: bcrypt.hashSync('1234567890'),
            isAdmin: true,
        },
        {
            name: 'Test User1',
            email: 'tuser1@fhub.com',
            password: bcrypt.hashSync('1234567890'),
            isAdmin: false,
        }
    ],
    products: [
        {
            //_id: "101",
            slug: 'Mens-Basic-Tee-Black',
            gender: "Men",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Basic Tee Black',
            price: 15.00,
            color: 'Black',
            src: 'Mens-BasicT-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "102",
            slug: 'Mens-Basic-Tee-White',
            gender: "Men",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Basic Tee White',
            price: 15.00,
            color: 'White',
            src: 'Mens-BasicT-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "103",
            slug: 'Mens-Basic-Tee-Grey',
            gender: "Men",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Basic Tee Grey',
            price: 15.00,
            color: 'Grey',
            src: 'Mens-BasicT-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "104",
            slug: 'Mens-Basic-Tee-SkyBlue',
            gender: "Men",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Basic Tee SkyBlue',
            price: 15.00,
            color: 'SkyBlue',
            src: 'Mens-BasicT-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "105",
            slug: 'Mens-Hoodie-Black',
            gender: "Men",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'Hoodie Black',
            price: 35.00,
            color: 'Black',
            src: 'Mens-Hoodie-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "106",
            slug: 'Mens-Hoodie-Grey',
            gender: "Men",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'Hoodie Grey',
            price: 35.00,
            color: 'Grey',
            src: 'Mens-Hoodie-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "107",
            slug: 'Mens-Hoodie-Purple',
            gender: "Men",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'Hoodie Purple',
            price: 35.00,
            color: 'Purple',
            src: 'Mens-Hoodie-Purple.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "108",
            slug: 'Mens-Hoodie-SkyBlue',
            gender: "Men",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'Hoodie SkyBlue',
            price: 35.00,
            color: 'SkyBlue',
            src: 'Mens-Hoodie-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "109",
            slug: 'Mens-Hoodie-Tan',
            gender: "Men",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'Hoodie Tan',
            price: 35.00,
            color: 'Tan',
            src: 'Mens-Hoodie-Tan.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "110",
            slug: 'Mens-Sweat-Shirt-Black',
            gender: 'Men',
            category: 'Sweat-Shirts',
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Sweat Shirt Black',
            price: 25.00,
            color: 'Black',
            src: 'Mens-LSleeveT-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "111",
            slug: 'Mens-Sweat-Shirt-Grey',
            gender: "Men",
            category: "Sweat-Shirts",
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Sweat Shirt Grey',
            price: 25.00,
            color: 'Grey',
            src: 'Mens-LSleeveT-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "112",
            slug: 'Mens-Sweat-Shirt-Tan',
            gender: "Men",
            category: "Sweat-Shirts",
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Sweat Shirt Tan',
            price: 25.00,
            color: 'Tan',
            src: 'Mens-LSleeveT-Tan.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "113",
            slug: 'Mens-Sweat-Shirt-White',
            gender: "Men",
            category: "Sweat-Shirts",
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Sweat Shirt White',
            price: 25.00,
            color: 'White',
            src: 'Mens-LSleeveT-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "114",
            slug: 'Mens-Polo-T-Shirt-Purple',
            gender: "Men",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: true,
            discount: 25,
            title: 'Polo T-Shirt Purple',
            price: 20.00,
            color: 'Purple',
            src: 'Mens-PoloT-Strip.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "115",
            slug: 'Mens-Shirt-Blue',
            gender: "Men",
            category: "Shirts",
            collectionSeason: 'Fall',
            onSale: true,
            discount: 25,
            title: 'Shirt Blue',
            price: 25.00,
            color: 'Blue',
            src: 'Mens-Shirt-Blue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "116",
            slug: 'Mens-Shirt-White',
            gender: "Men",
            category: "Shirts",
            collectionSeason: 'Fall',
            onSale: true,
            discount: 25,
            title: 'Shirt White',
            price: 25.00,
            color: 'White',
            src: 'Mens-Shirt-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "117",
            slug: 'Mens-Jeans-Black',
            gender: "Men",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Jeans Black',
            price: 30.00,
            color: 'Black',
            src: 'Mens-Jeans-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "118",
            slug: 'Mens-Jeans-Blue',
            gender: "Men",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Jeans Blue',
            price: 30.00,
            color: 'Blue',
            src: 'Mens-Jeans-Blue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "119",
            slug: 'Mens-Jeans-SkyBlue',
            gender: "Men",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Jeans SkyBlue',
            price: 30.00,
            color: 'SkyBlue',
            src: 'Mens-Jeans-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "120",
            slug: 'Mens-Shorts-Black',
            gender: "Men",
            category: "Shorts",
            collectionSeason: "Fall",
            onSale: true,
            discount: 25,
            title: 'Shorts Black',
            price: 15.00,
            color: 'Black',
            src: 'Mens-Short-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "121",
            slug: 'Mens-Shorts-White',
            gender: "Men",
            category: "Shorts",
            collectionSeason: "Fall",
            onSale: true,
            discount: 25,
            title: 'Shorts White',
            price: 15.00,
            color: 'White',
            src: 'Mens-Short-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "122",
            slug: 'Mens-Track-Pants-Black',
            gender: "Men",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'Track Pant Black',
            price: 15.00,
            color: 'Black',
            src: 'Mens-Track-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "123",
            slug: 'Mens-Track-Pants-Grey',
            gender: "Men",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'Track Pant Grey',
            price: 15.00,
            color: 'Grey',
            src: 'Mens-Track-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "124",
            slug: 'Mens-Track-Pants-Tan',
            gender: "Men",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'Track Pant Tan',
            price: 15.00,
            color: 'Tan',
            src: 'Mens-Track-Tan.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "125",
            slug: 'Mens-Beanie-Black',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "Winter",
            onSale: true,
            discount: 15,
            title: 'Beanie Black',
            price: 10.00,
            color: 'Black',
            src: 'Mens-Beanie-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "126",
            slug: 'Mens-Beanie-Grey',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "Winter",
            onSale: true,
            discount: 15,
            title: 'Beanie Grey',
            price: 10.00,
            color: 'Grey',
            src: 'Mens-Beanie-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "127",
            slug: 'Mens-Cap-Black',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "Summer",
            onSale: false,
            discount: 0,
            title: 'Hollister Cap Black',
            price: 15.00,
            color: 'Black',
            src: 'Mens-Cap-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "128",
            slug: 'Mens-Cap-White',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "Summer",
            onSale: false,
            discount: 0,
            title: 'Hollister Cap White',
            price: 15.00,
            color: 'White',
            src: 'Mens-Cap-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "149",
            slug: 'Mens-Shoes-Grey',
            gender: "Men",
            category: "Footwear",
            collectionSeason: "General",
            onSale: true,
            discount: 50,
            title: 'Adidas Shoes Grey',
            price: 50.00,
            color: 'Grey',
            src: 'Mens-Shoes-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "150",
            slug: 'Mens-Shoes-Black',
            gender: "Men",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'Adidas Shoes Black',
            price: 50.00,
            color: 'Black',
            src: 'Mens-Shoes-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "151",
            slug: 'Mens-Shoes-White',
            gender: "Men",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'Adidas Shoes White',
            price: 50.00,
            color: 'White',
            src: 'Mens-Shoes-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "152",
            slug: 'Mens-Slippers-Black',
            gender: "Men",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'Slippers Black',
            price: 25.00,
            color: 'Black',
            src: 'Mens-Slippers-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "153",
            slug: 'Mens-Slippers-White',
            gender: "Men",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'Slippers White',
            price: 25.00,
            color: 'White',
            src: 'Mens-Slippers-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "129",
            slug: 'Mens-Fanny-Pack-Black',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'Fanny Pack Black',
            price: 20.00,
            color: 'Black',
            src: 'Mens-FannyPack-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "130",
            slug: 'Mens-Leather-Belt-Black',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'Leather Belt Black',
            price: 25.00,
            color: 'Black',
            src: 'Mens-LeatherBelt-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "131",
            slug: 'Mens-Leather-Belt-Brown',
            gender: "Men",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'Leather Belt Brown',
            price: 25.00,
            color: 'Brown',
            src: 'Mens-LeatherBelt-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "201",
            slug: 'Womens-Graphic-Tee-White',
            gender: "Women",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Graphic Tee White',
            price: 15.00,
            color: 'White',
            src: 'Womens-GraphicT-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "202",
            slug: 'Womens-Graphic-Tee-Olive-Green',
            gender: "Women",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Graphic Tee Green',
            price: 15.00,
            color: 'Olive Green',
            src: 'Womens-GraphicT-OGreen.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "203",
            slug: 'Womens-Graphic-Tee-Grey',
            gender: "Women",
            category: "T-Shirts",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'Graphic Tee Grey',
            price: 15.00,
            color: 'Grey',
            src: 'Womens-GraphicT-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "204",
            slug: 'Womens-Hoodie-Black',
            gender: "Women",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'F Hoodie Black',
            price: 35.00,
            color: 'Black',
            src: 'Womens-Hoodie-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "205",
            slug: 'Womens-Hoodie-Pink',
            gender: "Women",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'F Hoodie Pink',
            price: 35.00,
            color: 'Pink',
            src: 'Womens-Hoodie-Pink.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "206",
            slug: 'Womens-Hoodie-Tan',
            gender: "Women",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'F Hoodie Tan',
            price: 35.00,
            color: 'Tan',
            src: 'Womens-Hoodie-Tan.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "207",
            slug: 'Womens-Hoodie-White',
            gender: "Women",
            category: "Hoodies",
            collectionSeason: 'Winter',
            onSale: true,
            discount: 25,
            title: 'F Hoodie White',
            price: 35.00,
            color: 'White',
            src: 'Womens-Hoodie-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "208",
            slug: 'Womens-Long-Sleeve-T-Shirt-Black',
            gender: 'Women',
            category: 'T-Shirts',
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Long Sleeve T-Shirt Black',
            price: 25.00,
            color: 'Black',
            src: 'Womens-LSleeveT-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "209",
            slug: 'Womens-Long-Sleeve-T-Shirt-Pink',
            gender: "Women",
            category: 'T-Shirts',
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Long Sleeve T-Shirt Pink',
            price: 25.00,
            color: 'Pink',
            src: 'Womens-LSleeveT-Pink.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "210",
            slug: 'Womens-Long-Sleeve-T-Shirt-White',
            gender: "Women",
            category: 'T-Shirts',
            collectionSeason: 'Fall',
            onSale: false,
            discount: 0,
            title: 'Long Sleeve T-Shirt White',
            price: 25.00,
            color: 'White',
            src: 'Womens-LSleeveT-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "211",
            slug: 'Womens-Jeans-Black',
            gender: "Women",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'F Jeans Black',
            price: 30.00,
            color: 'Black',
            src: 'Womens-Jeans-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "212",
            slug: 'Womens-Jeans-Blue',
            gender: "Women",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'F Jeans Blue',
            price: 30.00,
            color: 'Blue',
            src: 'Womens-Jeans-Blue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "213",
            slug: 'Womens-Jeans-SkyBlue',
            gender: "Women",
            category: "Pants",
            collectionSeason: 'Summer',
            onSale: false,
            discount: 0,
            title: 'F Jeans SkyBlue',
            price: 30.00,
            color: 'SkyBlue',
            src: 'Womens-Jeans-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "214",
            slug: 'Womens-Shorts-Brown',
            gender: "Women",
            category: "Shorts",
            collectionSeason: "Fall",
            onSale: true,
            discount: 25,
            title: 'F Shorts Brown',
            price: 15.00,
            color: 'Brown',
            src: 'Womens-Short-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "215",
            slug: 'Womens-Shorts-Grey',
            gender: "Women",
            category: "Shorts",
            collectionSeason: "Fall",
            onSale: true,
            discount: 25,
            title: 'F Shorts Grey',
            price: 15.00,
            color: 'Grey',
            src: 'Womens-Short-Grey.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "216",
            slug: 'Womens-Shorts-SkyBlue',
            gender: "Women",
            category: "Shorts",
            collectionSeason: "Fall",
            onSale: true,
            discount: 25,
            title: 'F Shorts SkyBlue',
            price: 15.00,
            color: 'SkyBlue',
            src: 'Womens-Short-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "217",
            slug: 'Womens-Track-Pants-Black',
            gender: "Women",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'F Track Pant Black',
            price: 15.00,
            color: 'Black',
            src: 'Womens-Track-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "218",
            slug: 'Womens-Track-Pants-SkyBlue',
            gender: "Women",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'F Track Pant SkyBlue',
            price: 15.00,
            color: 'SkyBlue',
            src: 'Womens-Track-SkyBlue.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "219",
            slug: 'Womens-Track-Pants-White',
            gender: "Women",
            category: "Pants",
            collectionSeason: "Winter",
            onSale: true,
            discount: 35,
            title: 'F Track Pant White',
            price: 15.00,
            color: 'White',
            src: 'Womens-Track-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "220",
            slug: 'Womens-Bucket-Hat-Brown',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "Summer",
            onSale: true,
            discount: 15,
            title: 'Bucket Hat Brown',
            price: 10.00,
            color: 'Brown',
            src: 'Womens-BucketHat-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "221",
            slug: 'Womens-Bucket-Hat-Creme',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "Summer",
            onSale: true,
            discount: 15,
            title: 'Bucket Hat Creme',
            price: 10.00,
            color: 'Creme',
            src: 'Womens-BucketHat-Creme.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "222",
            slug: 'Womens-Shoes-Pink',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: true,
            discount: 50,
            title: 'F Adidas Shoes Pink',
            price: 50.00,
            color: 'Pink',
            src: 'Womens-Shoes-Pink.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "223",
            slug: 'Womens-Shoes-White',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: true,
            discount: 50,
            title: 'F Adidas Shoes White',
            price: 50.00,
            color: 'White',
            src: 'Womens-Shoes-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "224",
            slug: 'Womens-Slippers-Black',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'F Slippers Black',
            price: 25.00,
            color: 'Black',
            src: 'Womens-Slippers-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "225",
            slug: 'Womens-Slippers-Brown',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'F Slippers Brown',
            price: 25.00,
            color: 'Brown',
            src: 'Womens-Slippers-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "226",
            slug: 'Womens-Slippers-White',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'F Slippers White',
            price: 25.00,
            color: 'White',
            src: 'Womens-Slippers-White.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "227",
            slug: 'Womens-Leather-FlipFlops-Brown',
            gender: "Women",
            category: "Footwear",
            collectionSeason: "General",
            onSale: false,
            discount: 0,
            title: 'Leather FlipFlops Brown',
            price: 25.00,
            color: 'Brown',
            src: 'Womens-LeatherFlipFlops-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "228",
            slug: 'Womens-Leather-Belt-Black',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'F Leather Belt Black',
            price: 25.00,
            color: 'Black',
            src: 'Womens-LeatherBelt-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "229",
            slug: 'Womens-Leather-Belt-Brown',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'F Leather Belt Brown',
            price: 25.00,
            color: 'Brown',
            src: 'Womens-LeatherBelt-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "230",
            slug: 'Womens-Mini-Backpack-Black',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'Mini Backpack Black',
            price: 25.00,
            color: 'Black',
            src: 'Womens-MiniBackpack-Black.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        },
        {
            //_id: "231",
            slug: 'Womens-Mini-Backpack-Brown',
            gender: "Women",
            category: "Accessories",
            collectionSeason: "General",
            onSale: true,
            discount: 10,
            title: 'Mini Backpack Brown',
            price: 25.00,
            color: 'Brown',
            src: 'Womens-MiniBackpack-Brown.jpg',
            quantityInStock: 10,
            ratings: 4.5,
            numOfReviews: 10,
            description: '100% Cotton Material'
        }
    ],

}