export const data = {
    men: [
            {
                id: 101,
                slug: 'Basic-Tee-Black',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'Black',
                src: 'assets/products/men/BasicT-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 102,
                slug: 'Basic-Tee-White',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'White',
                src: 'assets/products/men/BasicT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 103,
                slug: 'Basic-Tee-Grey',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'Grey',
                src: 'assets/products/men/BasicT-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 104,
                slug: 'Basic-Tee-SkyBlue',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'SkyBlue',
                src: 'assets/products/men/BasicT-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 105,
                slug: 'Hoodie-Black',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Black',
                src: 'assets/products/men/Hoodie-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 106,
                slug: 'Hoodie-Grey',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Grey',
                src: 'assets/products/men/Hoodie-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 107,
                slug: 'Hoodie-Purple',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Purple',
                src: 'assets/products/men/Hoodie-Purple.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 108,
                slug: 'Hoodie-SkyBlue',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'SkyBlue',
                src: 'assets/products/men/Hoodie-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 109,
                slug: 'Hoodie-Tan',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Tan',
                src: 'assets/products/men/Hoodie-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 110,
                slug: 'Sweat-Shirt-Black',
                gender: 'Men',
                category: 'Sweat-Shirts',
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/men/LSleeveT-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 111,
                slug: 'Sweat-Shirt-Grey',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Grey',
                src: 'assets/products/men/LSleeveT-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 112,
                slug: 'Sweat-Shirt-Tan',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Tan',
                src: 'assets/products/men/LSleeveT-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 113,
                slug: 'Sweat-Shirt-White',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'White',
                src: 'assets/products/men/LSleeveT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 114,
                slug: 'Polo-T-Shirt-Purple',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Polo T-Shirt',
                price: 20.00,
                color: 'Purple',
                src: 'assets/products/men/PoloT-Strip.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 115,
                slug: 'Shirt-Blue',
                gender: "Men",
                category: "Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shirt',
                price: 25.00,
                color: 'Blue',
                src: 'assets/products/men/Shirt-Blue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 116,
                slug: 'Shirt-White',
                gender: "Men",
                category: "Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shirt',
                price: 25.00,
                color: 'White',
                src: 'assets/products/men/Shirt-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 117,
                slug: 'Jeans-Black',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Black',
                src: 'assets/products/men/Jeans-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 118,
                slug: 'Jeans-Blue',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Blue',
                src: 'assets/products/men/Jeans-Blue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 119,
                slug: 'Jeans-SkyBlue',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'SkyBlue',
                src: 'assets/products/men/Jeans-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 120,
                slug: 'Shorts-Black',
                gender: "Men",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'Black',
                src: 'assets/products/men/Short-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 121,
                slug: 'Shorts-White',
                gender: "Men",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'White',
                src: 'assets/products/men/Short-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 122,
                slug: 'Track-Pants-Black',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Black',
                src: 'assets/products/men/Track-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 123,
                slug: 'Track-Pants-Grey',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Grey',
                src: 'assets/products/men/Track-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 124,
                slug: 'Track-Pants-Tan',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Tan',
                src: 'assets/products/men/Track-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 125,
                slug: 'Beanie-Black',
                gender: "Men",
                category: "Accessories",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Beanie',
                price: 10.00,
                color: 'Black',
                src: 'assets/products/men/Beanie-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 126,
                slug: 'Beanie-Grey',
                gender: "Men",
                category: "Accessories",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Beanie',
                price: 10.00,
                color: 'Grey',
                src: 'assets/products/men/Beanie-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 127,
                slug: 'Cap-Black',
                gender: "Men",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Hollister Cap',
                price: 15.00,
                color: 'Black',
                src: 'assets/products/men/Cap-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 128,
                slug: 'Cap-White',
                gender: "Men",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Hollister Cap',
                price: 15.00,
                color: 'White',
                src: 'assets/products/men/Cap-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 149,
                slug: 'Shoes-Grey',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 50
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'Grey',
                src: 'assets/products/men/Shoes-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 150,
                slug: 'Shoes-Black',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'Black',
                src: 'assets/products/men/Shoes-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 151,
                slug: 'Shoes-White',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'White',
                src: 'assets/products/men/Shoes-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 152,
                slug: 'Slippers-Black',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/men/Slippers-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 153,
                slug: 'Slippers-White',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'White',
                src: 'assets/products/men/Slippers-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 129,
                slug: 'Fanny-Pack-Black',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Fanny Pack',
                price: 20.00,
                color: 'Black',
                src: 'assets/products/men/FannyPack-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 130,
                slug: 'Leather-Belt-Black',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/men/LeatherBelt-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 131,
                slug: 'Leather-Belt-Brown',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Brown',
                src: 'assets/products/men/LeatherBelt-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            }  
        ],
    
        women: [
            {
                id: 201,
                slug: 'Graphic-Tee-White',
                gender: "Women",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Graphic Tee',
                price: 15.00,
                color: 'White',
                src: 'assets/products/women/GraphicT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 202,
                slug: 'Graphic-Tee-Olive-Green',
                gender: "Women",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Graphic Tee',
                price: 15.00,
                color: 'Olive Green',
                src: 'assets/products/women/GraphicT-OGreen.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 203,
                slug: 'Graphic-Tee-Grey',
                gender: "Women",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Graphic Tee',
                price: 15.00,
                color: 'Grey',
                src: 'assets/products/women/GraphicT-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 204,
                slug: 'Hoodie-Black',
                gender: "Women",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Black',
                src: 'assets/products/women/Hoodie-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 205,
                slug: 'Hoodie-Pink',
                gender: "Women",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Pink',
                src: 'assets/products/women/Hoodie-Pink.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 206,
                slug: 'Hoodie-Tan',
                gender: "Women",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Tan',
                src: 'assets/products/women/Hoodie-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 207,
                slug: 'Hoodie-White',
                gender: "Women",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'White',
                src: 'assets/products/women/Hoodie-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 208,
                slug: 'Long-Sleeve-T-Shirt-Black',
                gender: 'Women',
                category: 'T-Shirts',
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Long Sleeve T-Shirt',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/women/LSleeveT-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 209,
                slug: 'Long-Sleeve-T-Shirt-Pink',
                gender: "Women",
                category: 'T-Shirts',
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Long Sleeve T-Shirt',
                price: 25.00,
                color: 'Pink',
                src: 'assets/products/women/LSleeveT-Pink.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 210,
                slug: 'Long-Sleeve-T-Shirt-White',
                gender: "Women",
                category: 'T-Shirts',
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Long Sleeve T-Shirt',
                price: 25.00,
                color: 'White',
                src: 'assets/products/women/LSleeveT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 211,
                slug: 'Jeans-Black',
                gender: "Women",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Black',
                src: 'assets/products/women/Jeans-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 212,
                slug: 'Jeans-Blue',
                gender: "Women",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Blue',
                src: 'assets/products/women/Jeans-Blue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 213,
                slug: 'Jeans-SkyBlue',
                gender: "Women",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'SkyBlue',
                src: 'assets/products/women/Jeans-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 214,
                slug: 'Shorts-Brown',
                gender: "Women",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'Brown',
                src: 'assets/products/women/Short-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 215,
                slug: 'Shorts-Grey',
                gender: "Women",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'Grey',
                src: 'assets/products/women/Short-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 216,
                slug: 'Shorts-SkyBlue',
                gender: "Women",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'SkyBlue',
                src: 'assets/products/women/Short-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 217,
                slug: 'Track-Pants-Black',
                gender: "Women",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Black',
                src: 'assets/products/women/Track-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 218,
                slug: 'Track-Pants-SkyBlue',
                gender: "Women",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'SkyBlue',
                src: 'assets/products/women/Track-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 219,
                slug: 'Track-Pants-White',
                gender: "Women",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'White',
                src: 'assets/products/women/Track-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 220,
                slug: 'Bucket-Hat-Brown',
                gender: "Women",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Bucket Hat',
                price: 10.00,
                color: 'Brown',
                src: 'assets/products/women/BucketHat-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 221,
                slug: 'Bucket-Hat-Creme',
                gender: "Women",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Bucket Hat',
                price: 10.00,
                color: 'Creme',
                src: 'assets/products/women/BucketHat-Creme.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 222,
                slug: 'Shoes-Pink',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 50
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'Pink',
                src: 'assets/products/women/Shoes-Pink.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 223,
                slug: 'Shoes-White',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 50
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'White',
                src: 'assets/products/women/Shoes-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 224,
                slug: 'Slippers-Black',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/women/Slippers-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 225,
                slug: 'Slippers-Brown',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'Brown',
                src: 'assets/products/women/Slippers-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 226,
                slug: 'Slippers-White',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'White',
                src: 'assets/products/women/Slippers-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 227,
                slug: 'Leather-FlipFlops-Brown',
                gender: "Women",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Leather FlipFlops',
                price: 25.00,
                color: 'Brown',
                src: 'assets/products/women/LeatherFlipFlops-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 228,
                slug: 'Leather-Belt-Black',
                gender: "Women",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/women/LeatherBelt-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 229,
                slug: 'Leather-Belt-Brown',
                gender: "Women",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Brown',
                src: 'assets/products/women/LeatherBelt-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 230,
                slug: 'Mini-Backpack-Black',
                gender: "Women",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Mini Backpack',
                price: 25.00,
                color: 'Black',
                src: 'assets/products/women/MiniBackpack-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 231,
                slug: 'Mini-Backpack-Brown',
                gender: "Women",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Mini Backpack',
                price: 25.00,
                color: 'Brown',
                src: 'assets/products/women/MiniBackpack-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            }    
        ]
}