export const data = {
    products: [
            {
                id: 101,
                slug: 'Basic-Tee-Black',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'Black',
                src: 'assets/men/BasicT-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 102,
                slug: 'Basic-Tee-White',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'White',
                src: 'assets/men/BasicT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 103,
                slug: 'Basic-Tee-Grey',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'Grey',
                src: 'assets/men/BasicT-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 104,
                slug: 'Basic-Tee-SkyBlue',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Basic Tee',
                price: 15.00,
                color: 'SkyBlue',
                src: 'assets/men/BasicT-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 105,
                slug: 'Hoodie-Black',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Black',
                src: 'assets/men/Hoodie-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 106,
                slug: 'Hoodie-Grey',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Grey',
                src: 'assets/men/Hoodie-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 107,
                slug: 'Hoodie-Purple',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Purple',
                src: 'assets/men/Hoodie-Purple.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 108,
                slug: 'Hoodie-SkyBlue',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'SkyBlue',
                src: 'assets/men/Hoodie-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 109,
                slug: 'Hoodie-Tan',
                gender: "Men",
                category: "Hoodies",
                collection: 'Winter',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Hoodie',
                price: 35.00,
                color: 'Tan',
                src: 'assets/men/Hoodie-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 110,
                slug: 'Sweat-Shirt-Black',
                gender: 'Men',
                category: 'Sweat-Shirts',
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Black',
                src: 'assets/men/LSleeveT-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 111,
                slug: 'Sweat-Shirt-Grey',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Grey',
                src: 'assets/men/LSleeveT-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 112,
                slug: 'Sweat-Shirt-Tan',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'Tan',
                src: 'assets/men/LSleeveT-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 113,
                slug: 'Sweat-Shirt-White',
                gender: "Men",
                category: "Sweat-Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Sweat Shirt',
                price: 25.00,
                color: 'White',
                src: 'assets/men/LSleeveT-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 114,
                slug: 'Polo-T-Shirt-Purple',
                gender: "Men",
                category: "T-Shirts",
                collection: 'Summer',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Polo T-Shirt',
                price: 20.00,
                color: 'Purple',
                src: 'assets/men/PoloT-Strip.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 115,
                slug: 'Shirt-Blue',
                gender: "Men",
                category: "Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shirt',
                price: 25.00,
                color: 'Blue',
                src: 'assets/men/Shirt-Blue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 116,
                slug: 'Shirt-White',
                gender: "Men",
                category: "Shirts",
                collection: 'Fall',
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shirt',
                price: 25.00,
                color: 'White',
                src: 'assets/men/Shirt-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 117,
                slug: 'Jeans-Black',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Black',
                src: 'assets/men/Jeans-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 118,
                slug: 'Jeans-Blue',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'Blue',
                src: 'assets/men/Jeans-Blue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 119,
                slug: 'Jeans-SkyBlue',
                gender: "Men",
                category: "Pants",
                collection: 'Summer',
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Jeans',
                price: 30.00,
                color: 'SkyBlue',
                src: 'assets/men/Jeans-SkyBlue.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 120,
                slug: 'Shorts-Black',
                gender: "Men",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'Black',
                src: 'assets/men/Short-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 121,
                slug: 'Shorts-White',
                gender: "Men",
                category: "Shorts",
                collection: "Fall",
                promotion: {
                                onSale: true,
                                discount: 25
                            },
                title: 'Shorts',
                price: 15.00,
                color: 'White',
                src: 'assets/men/Short-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 122,
                slug: 'Track-Pants-Black',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Black',
                src: 'assets/men/Track-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 123,
                slug: 'Track-Pants-Grey',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Grey',
                src: 'assets/men/Track-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 124,
                slug: 'Track-Pants-Tan',
                gender: "Men",
                category: "Pants",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 35
                            },
                title: 'Track Pants',
                price: 15.00,
                color: 'Tan',
                src: 'assets/men/Track-Tan.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 125,
                slug: 'Beanie-Black',
                gender: "Men",
                category: "Accessories",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Beanie',
                price: 10.00,
                color: 'Black',
                src: 'assets/men/Beanie-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 126,
                slug: 'Beanie-Grey',
                gender: "Men",
                category: "Accessories",
                collection: "Winter",
                promotion: {
                                onSale: true,
                                discount: 15
                            },
                title: 'Beanie',
                price: 10.00,
                color: 'Grey',
                src: 'assets/men/Beanie-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 127,
                slug: 'Cap-Black',
                gender: "Men",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Hollister Cap',
                price: 15.00,
                color: 'Black',
                src: 'assets/men/Cap-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 128,
                slug: 'Cap-White',
                gender: "Men",
                category: "Accessories",
                collection: "Summer",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Hollister Cap',
                price: 15.00,
                color: 'White',
                src: 'assets/men/Cap-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 149,
                slug: 'Shoes-Grey',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 50
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'Grey',
                src: 'assets/men/Shoes-Grey.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 150,
                slug: 'Shoes-Black',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'Black',
                src: 'assets/men/Shoes-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 151,
                slug: 'Shoes-White',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Adidas Shoes',
                price: 50.00,
                color: 'White',
                src: 'assets/men/Shoes-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 152,
                slug: 'Slippers-Black',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'Black',
                src: 'assets/men/Slippers-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 153,
                slug: 'Slippers-White',
                gender: "Men",
                category: "Footwear",
                collection: "General",
                promotion: {
                                onSale: false,
                                discount: 0
                            },
                title: 'Slippers',
                price: 25.00,
                color: 'White',
                src: 'assets/men/Slippers-White.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 129,
                slug: 'Fanny-Pack-Black',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Fanny Pack',
                price: 20.00,
                color: 'Black',
                src: 'assets/men/FannyPack-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 130,
                slug: 'Leather-Belt-Black',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Black',
                src: 'assets/men/LeatherBelt-Black.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            },
            {
                id: 131,
                slug: 'Leather-Belt-Brown',
                gender: "Men",
                category: "Accessories",
                collection: "General",
                promotion: {
                                onSale: true,
                                discount: 10
                            },
                title: 'Leather Belt',
                price: 25.00,
                color: 'Brown',
                src: 'assets/men/LeatherBelt-Brown.jpg',
                quantityInStock: 10,
                ratings: 4.5,
                numOfReviews: 10,
            }  
        ]
}